version: '3.9'
services:
  pdns:
    build: testdata/pdns/docker
    ports:
      - '53:53/udp'
      - '53:53/tcp'
      - '8080:8080'
    volumes:
      - data:/data
    environment:
      - PDNS_API_KEY=test123
volumes:
  data: {}
